Definindo cores que serão utilizadas no projeto
```{r}
colors = c("#CC1011", "#665555", "#05a399", "#cfcaca", "#f5e840", "#0683c9", "#e075b0")
```
Importando dados
```{r}

apr_data = read.csv("./Uber-dataset/uber-raw-data-apr14.csv/uber-raw-data-apr14.csv")

aug_data = read.csv("./Uber-dataset/uber-raw-data-aug14.csv/uber-raw-data-aug14.csv")

jul_data = read.csv("./Uber-dataset/uber-raw-data-jul14.csv/uber-raw-data-jul14.csv")

jun_data = read.csv("./Uber-dataset/uber-raw-data-jun14.csv/uber-raw-data-jun14.csv")

may_data = read.csv("./Uber-dataset/uber-raw-data-may14.csv/uber-raw-data-may14.csv")

sep_data = read.csv("./Uber-dataset/uber-raw-data-sep14.csv/uber-raw-data-sep14.csv")


```
Combinando dados
```{r}

data_2014 = rbind(apr_data,may_data, jun_data, jul_data, aug_data, sep_data)

```
Manipulando Dados
```{r}

library(lubridate)

data_2014$Date.Time <- as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S")

data_2014$Time <- format(as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")

data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)

data_2014$day <- factor(day(data_2014$Date.Time))

data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))

data_2014$year <- factor(year(data_2014$Date.Time))

data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))

data_2014$hour <- factor(hour(hms(data_2014$Time)))

data_2014$minute <- factor(minute(hms(data_2014$Time)))

data_2014$second <- factor(second(hms(data_2014$Time)))

```
Visualizando dados
```{r}

library(dplyr)
library(DT)
library(ggplot2)
library(ggthemes)


# Plotando número de viagens que os passageiros realizaram por horas em um dia:

hour_data <- data_2014 %>%
              group_by(hour) %>%
                dplyr::summarize(Total = n())

datatable(hour_data)

ggplot(hour_data, aes(hour, Total)) + 
    geom_bar( stat = "identity", fill = "steelblue", color = "black") +
        ggtitle("Trips Every Hour") +
          theme(legend.position = "none")

month_hour <- data_2014 %>%
              group_by(month, hour) %>%
                 dplyr::summarize(Total = n())

ggplot(month_hour, aes(hour, Total, fill = month)) + 
  geom_bar( stat = "identity") +
    ggtitle("Trips by Hour and Month")


# Plotando número de viagens que os passageiros realizaram durante cada dia do mês:

day_group <- data_2014 %>%
  group_by(day) %>%
    dplyr::summarize(Total = n())

datatable(day_group)

ggplot(day_group, aes(day, Total)) + 
  geom_bar( stat = "identity", fill = "steelblue") +
    ggtitle("Trips Every Day") +
      theme(legend.position = "none")

# Separando por dia da semana:

day_month_group <- data_2014 %>%
  group_by(month, day) %>%
      dplyr::summarize(Total = n())

ggplot(day_month_group, aes(day, Total, fill = month)) + 
  geom_bar( stat = "identity") +
    ggtitle("Trips by Day and Month")
    scale_fill_manual(values = colors)
    
    
# Visulizando número de viagens em cada mês do ano
    
month_group <- data_2014 %>%
  group_by(month) %>%
    dplyr::summarize(Total = n())

datatable(month_group)
 
ggplot(month_group, aes(month, Total, fill = month)) + 
  geom_bar( stat = "identity") +
    ggtitle("Trips by Month") +
      theme(legend.position = "none") +
        scale_fill_manual(values = colors)

# Por dia da semana no mês e ano:

month_weekday <- data_2014 %>%
  group_by(month, dayofweek) %>%
    dplyr::summarize(Total = n())

ggplot(month_weekday, aes(month, Total, fill = dayofweek)) + 
  geom_bar( stat = "identity", position = "dodge") +
    ggtitle("Trips by Day and Month") +
      scale_fill_manual(values = colors)


----------------------------------------------------

# Visualizando número de viagens por cada Base
    
ggplot(data_2014, aes(Base)) + 
  geom_bar(fill = "darkred") +
  ggtitle("Trips by Bases")

# Viagens por Base e mês:

ggplot(data_2014, aes(Base, fill = month)) + 
  geom_bar(position = "dodge") +
  ggtitle("Trips by Bases and Month") +
  scale_fill_manual(values = colors)

# Por dia da semana e Base
    
ggplot(data_2014, aes(Base, fill = dayofweek)) + 
  geom_bar(position = "dodge") +
  ggtitle("Trips by Bases and DayofWeek") +
  scale_fill_manual(values = colors)

----------------------------------------------------    

# Visualizando um mapa com as viagens    

min_lat <- 40.5774
max_lat <- 40.9176
min_long <- -74.15
max_long <- -73.7004
    
ggplot(data_2014, aes(x=Lon, y=Lat)) +
  geom_point(size=1, color = "blue") +
    scale_x_continuous(limits=c(min_long, max_long)) +
      scale_y_continuous(limits=c(min_lat, max_lat)) +
        theme_map() +
          ggtitle("NYC MAP BASED ON UBER RIDES DURING 2014 (APR-SEP)")

# Por Base    

ggplot(data_2014, aes(x=Lon, y=Lat, color = Base)) +
  geom_point(size=1) +
    scale_x_continuous(limits=c(min_long, max_long)) +
      scale_y_continuous(limits=c(min_lat, max_lat)) +
        theme_map() +
          ggtitle("NYC MAP BASED ON UBER RIDES DURING 2014 (APR-SEP) by BASE")
    

```
Créditos para a equipe do DataFlair, cujos dados e análises para este projeto foram inspirados em uma postagem divulgada no site: https://data-flair.training/blogs/r-data-science-project-uber-data-analysis/